/*
 * hamming_distance.h
 */

#ifndef HAMMING_DISTANCE_DRIVER_H
#define HAMMING_DISTANCE_DRIVER_H

#define HAMMING_DISTANCE_BASEADDRESS      0x81100000
#define HAMMING_DISTANCE_REG0_ADDRESS     (HAMMING_DISTANCE_BASEADDRESS + 0*4)
#define HAMMING_DISTANCE_REG1_ADDRESS     (HAMMING_DISTANCE_BASEADDRESS + 1*4)
#define HAMMING_DISTANCE_REG2_ADDRESS     (HAMMING_DISTANCE_BASEADDRESS + 2*4)

#define HAMMING_DISTANCE_OPERAND_X  (*(volatile unsigned int *) HAMMING_DISTANCE_REG0_ADDRESS)
#define HAMMING_DISTANCE_OPERAND_Y  (*(volatile unsigned int *) HAMMING_DISTANCE_REG1_ADDRESS)
#define HAMMING_DISTANCE_OUT        (*(volatile unsigned int *) HAMMING_DISTANCE_REG2_ADDRESS)

#endif
  